site_name: Pypeln
repo_name: cgarciae/pypeln
repo_url: https://github.com/cgarciae/pypeln

theme:
  name: material

nav:
  - Introduction: index.md
  - Advanced Usage: advanced.md
  - API Reference:
      - process: api/process.md
      - thread: api/thread.md
      - task: api/task.md

extra:
  search:
    language: en
  social:
    - type: github
      link: https://github.com/cgarciae
    - type: twitter
      link: https://twitter.com/cgarciae88
    - type: linkedin
      link: https://www.linkedin.com/in/cgarciae

markdown_extensions:
  - admonition
  - codehilite

plugins:
  - search
  - mkdocstrings
